### ISSUE TITLE
Authentication and Security

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#13]
Make sure everything related to authentication is working as intended.
- Login forget password modal bug (see below)
- Cannot navigate to any page unless the user is logged in
- Hash and/or encrypt passwords

useful link: https://dayvster.com/blog/use-context-for-auth

**Comment by celinewmk** [comment]
![Screenshot 2023-07-13 at 20 47 40](https://github.com/kienmarkdo/uOBites/assets/71091659/c9cd1073-4949-47b1-a2c8-f860119b53f3)

only read the part about "Forgot password"

**Comment by AmyKKiti** [comment]
Login issue to fix: We don't want this to show up when we haven't entered anything in email box yet
![image](https://github.com/kienmarkdo/uOBites/assets/77587871/55ac67f9-64c9-498a-ab7f-d8862a7a739a)

**Comment by kienmarkdo** [comment]
We can close this now eh? The next person who reads this, if u dont see any issues, pls close it
