### ISSUE TITLE
[LANDING PAGE] Finish UI implementation

### ISSUE THREAD

**Issue by celinewmk** [kienmarkdo/uOBites#16]
This is the current UI:
![Screenshot 2023-07-13 at 20 36 40](https://github.com/kienmarkdo/uOBites/assets/71091659/c9c34e84-a110-4a0c-b92a-671873f433ab)

To do:
- Double-check that we have all the food outlets present ( related to #3 ): https://www.uottawa.ca/campus-life/sites/g/files/bhrskd281/files/2021-07/Where%20to%20eat%20-%20map%20EN-2021.pdf (Note: remember we only consider the food outlets that are actually near/on campus)
- Add icon on top right to let user view their profile
- Add logout button
- Change the names to follow the naming convention here: https://www.uottawa.ca/campus-life/eat-campus/where-eat
- Remove Thai Express as apparently, it's closed [DONE]
- Remove Go Cafe? (I think it's self-serving) [DONE]
- Add 305 Juice Bar and Pizza 800 [DONE]
- Have 2 instances of Tim Hortons: Tim Hortons (CRX), Tim Hortons (SITE) (maybe we should have a different tim hortons logo for each to make it more diverse lol) [DONE] 
- Improve the header of the page (optional)

**Comment by kienmarkdo** [comment]
- I merged my changes from `refactor-landing-kien` to `landing-page-amy`
    - Please feel free to test by clicking around and by reading the code
- I will now continue my work in the branch `menu-page-kien` to do menu routing
    - so when you click on a store image, it routes you to that specific store with the user's email
