### ISSUE TITLE
JSON files creation

### ISSUE THREAD

**Issue by celinewmk** [kienmarkdo/uOBites#18]
Create the json files to store information about all the food outlets, their location, opening hours, menu. I would suggest:
- One json for the store names, location, opening hours with an id, for example:
[{
    id: 1,
    name: "Starbucks",
    address: "blablab"
    Opening Hours: {
        "Monday": "10am - 4pm"
          ...
        "Sunday": "Closed".             
    }, {
    Another store here...etc
}]
(The opening hours can vary according to the store, we can decide to merge some days together if they have the same opening and closing time)

- Another json file with only the menu items (id has to match the id in the first json):
[{
    id: 1,
    menu: {
        "coffee": "5$",
        "frapuccino": "8$"
    }
etc..
}]

**Comment by kienmarkdo** [comment]
- Opening Hours can be **operationalHours** or **hoursOfOperation**
- ~~For menu, do we need to separate by category? Drinks in one place, burgers in one place....~~
    - Menu looks good. 
    - storeId instead of id, because it's like a "foreign key".
    - For price, just include the number. That way we can do math with the numbers more easily. In the frontend, we will add the $ sign.
