### ISSUE TITLE
[MENU PAGE] Add a Cart

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#28]
- _**Add to Cart**_
- _**Remove from Cart**_
- _**View Cart**_

- Payment (frontend, backend, DB)
    - Once Cart feature is done, we need to be able to make the Payment
- Order History (frontend, backend)
    - When Payment is done, we now just need to make a new UI page displays order and progress onto the screen

**Comment by celinewmk** [comment]
Items done:
- Add to cart 
- Remove from cart
- View cart
