### ISSUE TITLE
[MENU PAGE] Payment

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#29]
- Can make payment
- allow flex and credit card
- On the left we have the payment form, on the right we'll have the same cart as menu page but uneditable. We pass the cart as props from menu page
- Clicking pay, navigates to Order status
- Add button in Menu page to go to Checkout page

Related to https://github.com/kienmarkdo/uOBites/issues/28

**Comment by AmyKKiti** [comment]
todo:
- any login and prop passing from the previous menu page
- fix alignment
- fix cart
