### ISSUE TITLE
[ORDER HISTORY] UI Implementation

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#30]
Fetch and user's Order History.

~~Only do this after Payment is done https://github.com/kienmarkdo/uOBites/issues/29~~
Actually, you can populate the DB with Order Histories, then just do the frontend/backend :)

Make a new button in navbar for Order History page :)

**Comment by AmyKKiti** [comment]
[Closed because out of scope]

**Comment by AmyKKiti** [comment]
[Closed because out of scope]
Order status will be displayed after checkout and time to make will be randomized, that's all.
