### ISSUE TITLE
[MENU PAGE] Fix alignment of Menu and View Cart

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#35]
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/95f2d9be-88c0-41e3-b5e5-74a465c7efd5)
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/6402b756-35e3-4f05-b5cd-7768d6baa9b5)

![image](https://github.com/kienmarkdo/uOBites/assets/67518620/9fa41ffb-f434-44b0-bb1f-ca72ebcfe83b)

**Comment by celinewmk** [comment]
fixed
