### ISSUE TITLE
[DISCUSSION] Admin account

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#5]
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/2804048a-f272-4b34-94dc-55d940121001)

How will an admin account be created? Can users create an admin account or can we only create admin accounts in the codebase? If it's the latter, we do not need an email for admin account

Wait a minute... should username be the same as email??
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/2bb17605-f319-4599-8523-c8f85b494663)

**Comment by celinewmk** [comment]
- User cannot create an admin account, it does not make sense. So it's probably in the code base yes
- as for username, i can add a field for the username if it's needed (but we can have it as the email to make things simpler)

**Comment by kienmarkdo** [comment]
> * User cannot create an admin account, it does not make sense. So it's probably in the code base yes
> * as for username, i can add a field for the username if it's needed (but we can have it as the email to make things simpler)

Okay then I will remove the username field
