### ISSUE TITLE
[DISCUSSION] User Account -> Admin, Vendor, Customer

### ISSUE THREAD

**Issue by celinewmk** [kienmarkdo/uOBites#6]
I see that each type of account has a foreign key to user account, but shouldn't it be the opposite? User account has 3 foreign keys to each of the account. I just checked our DCMS project and this is how we did it. Additionally, maybe we also need an attribute `type_id` to differentiate between the types, so 0: admin, 1: vendor, 2:customer
![Screenshot 2023-06-30 at 10 47 06](https://github.com/kienmarkdo/uOBites/assets/71091659/b390ab1d-cedc-475c-a778-40a1f80afa86)
![Screenshot 2023-06-30 at 10 47 17](https://github.com/kienmarkdo/uOBites/assets/71091659/80705808-62f9-4275-a311-bce06a8f2c96)
![Screenshot 2023-06-30 at 10 47 24](https://github.com/kienmarkdo/uOBites/assets/71091659/2018cc7c-162b-4183-adc7-c8d3e0f79ee9)
![Screenshot 2023-06-30 at 10 47 33](https://github.com/kienmarkdo/uOBites/assets/71091659/11ba4509-17d1-4880-8937-730585d93e5b)

**Comment by kienmarkdo** [comment]
New redesign does not require this stuff anymore
