### ISSUE TITLE
[DISCUSSION] Food Order + Menu_item

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#7]
This is what it looks like right now.
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/947579dc-a57e-4925-af81-0c92819b44ce)

I feel like it should contain a list of all the food items that is in the order.
The example below shows an order of 2 burgers and 1 fries.
-> Burger ($9.99)
-> Burger ($9.99)
-> Fries ($4.99)
We can then calculate the total price ourselves in the backend.

Comment below if you guys want to do this or if you just want to have it as it is right now (display ONLY the total price and no other details of the food order).

It seems like Amy already considered this (see Amy's comments in Menu_item)
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/8bac107b-c5d5-4e77-bc29-ef5d0f004757)

PostgreSQL Arrays Documention: https://www.postgresql.org/docs/current/arrays.html

**Comment by celinewmk** [comment]
i agree that we should display a breakdown of the price

**Comment by kienmarkdo** [comment]
Looks like we'll need an array or a dictionary then. There's no way around this.

Brain storm suggestion:
```
2 arrays. Food_array, price_array.

When burger gets added, we do food_array.add("burger") and price_array("9.99")

or a dictionary,

{
    food_name: ["price", quantity] 
    burger: ["9.99", 2]
}
```
https://www.postgresql.org/docs/current/textsearch-dictionaries.html
https://www.postgresql.org/docs/current/arrays.html

**Comment by kienmarkdo** [comment]
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/ed41ba13-8687-400d-bfc8-ff85ecf8b7e3)

on the "Add to cart" page, it's just a page that displays a dropdown menu like Jordan said. 

We populate the "Add TO Cart" page with "Store 1's menu". We pass store_id to the "add to cart" page to know what menu items from the JSON file to populate onto the dropdown options.

**Comment by kienmarkdo** [comment]
Design has been changed a lot. See https://github.com/kienmarkdo/uOBites/issues/8
