### ISSUE TITLE
[NEW] New Design

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#8]
![image](https://github.com/kienmarkdo/uOBites/assets/67518620/6ee3cbb8-285b-4f24-89bb-1f74be196fa3)
---
DB should have
account information (user account)
order history
---

**Comment by celinewmk** [comment]
Are you going to also change the path where each screen goes to? (For the existing pages we have) I see that you're the assignee, I was gonna do it
