### ISSUE TITLE
[Registration page] Finalize details

### ISSUE THREAD

**Issue by kienmarkdo** [kienmarkdo/uOBites#9]
1. Fields should not accept strings longer than 255 chars 'cause database cannot take strings longer than 255 chars
2. Password should have min requirements (min length, etc. Maybe just min length = 6 for simplicity lol. No need for special chars, number, caps etc.)
3. Email field doesnt need red text cuz Bootstrap's <Form type="email"> component automatically handles it for us , but hey it looks pretty cool so we can just keep it :)
4. Handle whether a username already exists or not. "Error: this email is already registered" for example. Do we need to do password resets? 😭 prob not. Maybe just add "please contact administrator to recover your account"

Comment any concerns/updates below.

**Comment by celinewmk** [comment]
do we also need an exact length for the flex card?

**Comment by celinewmk** [comment]
For password, reset we could have a "Forgot password?", but yh it should be "please contact administrator to recover your account". I also think this item should be move with login feature
